# 数据库配置
spring:
  datasource:
    url: jdbc:mysql://192.168.1.138/suqinglin?useUnicode=true&characterEncoding=utf-8
    username: root
    password: xyzh2018
    driver-class-name: com.mysql.cj.jdbc.Driver
# thymeleaf
  thymeleaf:
    cache: false
# redis
  redis:
    host: 192.168.0.200
    port: 6379
    password: 12345
    database: 1
# 端口
server:
  port: 8888
# mapper位置
mybatis:
  mapper-locations:
    - classpath:mapper/*Mapper.xml